"""order

Revision ID: a77c4e05cfff
Revises: abd03b4e7e7b
Create Date: 2023-07-24 23:05:18.426881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77c4e05cfff'
down_revision = 'abd03b4e7e7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('tags', sa.Column('display', sa.String(length=320), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'display')
    op.drop_column('categories', 'order')
    # ### end Alembic commands ###
