"""init

Revision ID: abd03b4e7e7b
Revises: 9af8989b03f0
Create Date: 2023-07-22 18:47:27.077047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd03b4e7e7b'
down_revision = '9af8989b03f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_tags', sa.Column('title', sa.String(length=320), nullable=False))
    op.add_column('user_tags', sa.Column('title', sa.String(length=320), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tags', 'title')
    op.drop_column('chat_tags', 'title')
    # ### end Alembic commands ###
